name: Hello World

#on:
#  schedule:
#    #- cron:  '0 */12 * * *'
#    - cron:  '* * * * *'

on: [push]

jobs:
  one:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Hello
        env: 
          GITHUB_KEY: ${{ secrets.GITHUB_KEY }}
        run: |
          echo '# $(ssh-agent)'
          eval $(ssh-agent)
          echo '# ssh-add - <<< "${GITHUB_KEY}"'
          ssh-add - <<< "${GITHUB_KEY}"
          echo '# git config user.name "T-vK"'
          git config user.name "T-vK"
          echo '# git config user.email "t-vk@users.noreply.github.com"'
          git config user.email "t-vk@users.noreply.github.com"
          echo "Generated repo URL: git@github.com:${GITHUB_REPOSITORY}.git"
          echo '# git remote set-url origin "git@github.com:${GITHUB_REPOSITORY}.git"'
          git remote set-url origin "git@github.com:${GITHUB_REPOSITORY}.git"
          echo '# git tag 1.0'
          git tag 1.0
          echo '# git tag --list'
          git tag --list
          echo '# git push --tags'
          git push --tags
