name: Hello World

#on:
#  schedule:
#    #- cron:  '0 */12 * * *'
#    - cron:  '* * * * *'

on: [push]

jobs:
  one:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Hello
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a "/tmp/ssh_agent.sock" > /dev/null
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.GITHUB_KEY }}"
          git config user.name "T-vK"
          git config user.email "t-vk@users.noreply.github.com"
          echo "Generated repo URL: git@github.com:${GITHUB_REPOSITORY}.git"
          git remote set-url origin "git@github.com:${GITHUB_REPOSITORY}.git"
          git tag 1.0
          git tag --list
          git push --tags
